/**
 * REFSPACE.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TranslationDTO } from "./translationDTO";

export interface AttributeValueNamesDTO {
  /**
   * Identifier of the Attribute value.
   */
  id?: number;
  /**
   * Identifier of the Attribute id.
   */
  attributeId?: number;
  name?: TranslationDTO;
}
