/**
 * REFSPACE.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AttributeValueNamesDTO } from "./attributeValueNamesDTO";
import { TranslationDTO } from "./translationDTO";

export interface AttributeNameDTO {
  /**
   * Identifier of the Attribute.
   */
  id?: number;
  /**
   * Identifier of product.
   */
  productId?: number;
  name?: TranslationDTO;
  /**
   * List of values.
   */
  values: Array<AttributeValueNamesDTO>;
}
