/**
 * REFSPACE.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AttributeNameDTO } from "./attributeNameDTO";
import { PhotoResolutionDTO } from "./photoResolutionDTO";
import { PriceDTO } from "./priceDTO";

export interface CreatorProductRecomendationDTO {
  /**
   * Product name.
   */
  productName: string;
  /**
   * Creator product id
   */
  creatorProductId: number;
  /**
   * Product id
   */
  productId: number;
  /**
   * Available amount
   */
  availableAmount: number;
  /**
   * List of prices.
   */
  price: Array<PriceDTO>;
  /**
   * URL addresses of the thumbnail files.
   */
  thumbnails?: Array<PhotoResolutionDTO>;
  /**
   * ProductKey
   */
  productKey: string;
  /**
   * is favourite
   */
  isFavourite?: boolean;
  /**
   * is favourite
   */
  creatorId?: number;
  /**
   * List of video attribues. Can be empty.
   */
  attributes?: Array<AttributeNameDTO>;
}
