/**
 * REFSPACE.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { PhotoResolutionDTO } from "./photoResolutionDTO";
import { SocialMediaDTO } from "./socialMediaDTO";

export interface CreatorDetailsDTO {
  /**
   * Identifier of the creator.
   */
  id: number;
  /**
   * Name of the creator.
   */
  name: string;
  /**
   * URL address of the photo link file.
   */
  shopLinkViewPhotoUrl: string;
  /**
   * URL address of the photo link file.
   */
  cardLinkViewPhotoUrl: string;
  /**
   * URL address of profile photos.
   */
  profilePhotos: Array<PhotoResolutionDTO>;
  /**
   * Value indicating whether the creator is liked by the user.
   */
  isLiked: boolean;
  /**
   * Name of the creator.
   */
  creatorKey: string;
  /**
   * Amount of creator recommendations.
   */
  recommendationCount: number;
  /**
   * Amount of bonuses received by creator.
   */
  bonusCount: number;
  /**
   * Likes video Counts
   */
  likesCount: number;
  /**
   * Views video counts
   */
  viewsCount: number;
  /**
   * subscription count creator
   */
  creatorLikesCount: number;
  /**
   * URL address of creator background photo file.
   */
  backgroundPhotoUrl: string;
  /**
   * Description.
   */
  description: string;
  /**
   * Description.
   */
  seoDescription: string;
  /**
   * List of creator's social media.
   */
  socialMedia: Array<SocialMediaDTO>;
}
