/**
 * REFSPACE.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CreatorDetailsDTO } from "./creatorDetailsDTO";
import { CreatorProductRecomendationDTO } from "./creatorProductRecomendationDTO";
import { VideoRecommendationDTO } from "./videoRecommendationDTO";

export interface CreatorDetailsWithVideosDTO {
  /**
   * List of videos.
   */
  videos: Array<VideoRecommendationDTO>;
  /**
   * List of videos.
   */
  products: Array<CreatorProductRecomendationDTO>;
  creator: CreatorDetailsDTO;
}
