/**
 * REFSPACE.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Available currencies, namely:  0/Pln - Polish Zloty (PLN),  1/Eur - Euro (EUR),  2/Usd - American Dollar (USD).
 */
export type CurrencyEnum = "pln" | "eur" | "usd";

export const CurrencyEnum = {
  Pln: "pln" as CurrencyEnum,
  Eur: "eur" as CurrencyEnum,
  Usd: "usd" as CurrencyEnum,
};
