/**
 * REFSPACE.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Photo resolution width in pixels  36/PX36 -36 px width,  42/PX42 - 42 px width,  56/PX56 - 56 px width,  112/PX112 - 112 px width,  256/PX256 - 256 px width,  512/PX512 - 512 px width,  1024/PX51024 - 1024 px width,
 */
export type PhotoResolutionWidthEnum =
  | "pX36"
  | "pX42"
  | "pX56"
  | "pX112"
  | "pX256"
  | "pX512"
  | "pX1024";

export const PhotoResolutionWidthEnum = {
  PX36: "pX36" as PhotoResolutionWidthEnum,
  PX42: "pX42" as PhotoResolutionWidthEnum,
  PX56: "pX56" as PhotoResolutionWidthEnum,
  PX112: "pX112" as PhotoResolutionWidthEnum,
  PX256: "pX256" as PhotoResolutionWidthEnum,
  PX512: "pX512" as PhotoResolutionWidthEnum,
  PX1024: "pX1024" as PhotoResolutionWidthEnum,
};
