/**
 * REFSPACE.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Available social media for a creator, namely:  0/YouTube - YouTube,  1/Instagram - Instagram,  2/Facebook - Facebook,  3/TikTok - TikTok.
 */
export type SocialMediaEnum = "youTube" | "instagram" | "facebook" | "tikTok";

export const SocialMediaEnum = {
  YouTube: "youTube" as SocialMediaEnum,
  Instagram: "instagram" as SocialMediaEnum,
  Facebook: "facebook" as SocialMediaEnum,
  TikTok: "tikTok" as SocialMediaEnum,
};
