/**
 * REFSPACE.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { PhotoResolutionDTO } from "./photoResolutionDTO";

export interface VideoRecommendationDTO {
  /**
   * video id
   */
  id: number;
  /**
   * Title of the video.
   */
  videoTitle: string;
  /**
   * Video key: videotitle_id
   */
  videoKey: string;
  /**
   * URL addresses of the thumbnail files.
   */
  thumbnails: Array<PhotoResolutionDTO>;
  /**
   * is favourite
   */
  isFavourite?: boolean;
  /**
   * View counts
   */
  viewsCount?: number;
}
